
# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildWindows:
    runs-on: windows-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.1.5
      # Runs a set of commands using the runners shell
      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxelib install hxcpp > nul -quiet
          haxelib install lime -quiet
          haxelib install openfl 9.0.2 -quiet
          haxelib install flixel 4.8.1 -quiet
          haxelib install flixel-addons 2.9.0 -quiet
          haxelib install flixel-ui 2.3.3 -quiet
          haxelib install openfl-webm -quiet
          haxelib install actuate -quiet
          haxelib install hscript 2.4.0 -quiet
          haxelib install newgrounds 1.1.4 -quiet
          haxelib run lime setup -quiet
          haxelib install flixel-tools 1.4.4 -quiet
          haxelib list
        shell: cmd
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile
        run: haxelib run lime build windows --app-version="4.0.0-${{ github.run_id}}"
      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: windowsBuild
          path: export/release/windows/bin
